appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: HTac6dzDi+NpxCqiF8qj38AQH7D6ZOO1bZrriFmH/Pr1D319uA/Qt1NiFhYqqBnSQnUNuLKSQnLi0V90fioj5hfiH+GLNO4Ud0Bf+q9xl747edAGOMcuq+SOcOynh37hsuoAoxZEXS7yXGmYgwJmfOKWGdMeXyFNqxujWnkYbEkYzyaLpq9esRINUEGmfKZKmxtPWyOYvc1tgRMdRN5rRSDq6Pe8N0Ms3rey/bYE80PImJMkMFNqBJ7IzPKbeT8SvVBsABnz4e0bit6xxr2NeGckwl7BWC1IL6Vnk8lqN22V+xxtz47NibTckY2ZlMmK8mPx6F0zOABR4j1+hFbxlP5WltslO7DXtYIw6K0DjaFDjL2tYAqUallCc6gXFV50e9xSvkbTqVNRmhANUSFYMbvIbY14BR383zJ+CYzlk8fP5QqWZFJd0uPlhwPuthbRL7BcqXdvmzx0wCGDKcvLge8YlIiLttRPoWNm1wXQYFhUmiv4gamoSHlHNEBnc7Sgn1ZV7DJYqzT4+sf4udc9Y2w3bAPSVBnjNFYk2PDvP8EJAe2ESu3dw40mY4n4qVZnDJw+l09RcD6YMX6NeDOPuuQqXxTmsvMvdhBsSwmjhc3lJ9ccgfu0P2pZWYAgzhhW4fhosK3d6S9C6SYghNXveIhKJqYJTbAEjyds0j+ipkU=}
